openapi: 3.0.3
info:
  title: Mortgage API
  version: 1.0.0
paths:
  /interest-rates:
    get:
      summary: Get a list of current interest rates
      parameters:
        - $ref: '#/components/parameters/TraceId'
      responses:
        '200':
          description: A list of current interest rates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MortgageRatesResponse'
  /mortgage-check:
    post:
      summary: Calculate mortgage feasibility and monthly costs
      parameters:
        - $ref: '#/components/parameters/TraceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MortgageCheckRequest'
      responses:
        '200':
          description: Mortgage check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MortgageCheckResponse'
components:
  parameters:
    TraceId:
      name: X-Trace-Id
      in: header
      description: Unique identifier for tracing requests
      required: false
      schema:
        type: string
        format: uuid
  schemas:
    MortgageRatesResponse:
      type: object
      properties:
        rates:
          type: array
          items:
            $ref: '#/components/schemas/MortgageRate'
        traceId:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
    MortgageRate:
      type: object
      properties:
        maturityPeriod:
          type: integer
          example: 30
          minimum: 1
        interestRate:
          type: number
          format: double
          example: 3.5
          minimum: 0.0
          maximum: 100.0
    MortgageCheckRequest:
      type: object
      properties:
        loanValue:
          type: number
          format: double
          example: 1000.00
          minimum: 0.0
        maturityPeriod:
          type: integer
          example: 30
          minimum: 1
        income:
          type: number
          format: double
          example: 1000.00
          minimum: 0.0
        homeValue:
          type: number
          format: double
          example: 1000.00
          minimum: 0.0
      required:
        - income
        - maturityPeriod
        - loanValue
        - homeValue
    MortgageCheckResponse:
      type: object
      properties:
        feasible:
          type: boolean
          example: true
        monthlyCosts:
          type: number
          format: double
          example: 1000.00
        errorCodes:
          type: array
          items:
            type: string
            enum:
              - INSUFFICIENT_INCOME
              - HIGH_LOAN_TO_VALUE
        traceId:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      required:
        - feasible
        - monthlyCosts
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          example: INVALID_REQUEST
        message:
          type: string
          example: The request parameters are invalid.
        traceId:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      required:
        - errorCode
        - message
        - traceId